---
- name: restart apache2
  service:
    name: apache2
    state: restarted

- name: reload apache2
  service:
    name: apache2
    state: restarted

- name: restart httpd
  service:
    name: httpd
    state: restarted

- name: reload httpd
  service:
    name: httpd
    state: restarted
