---
- name: Enables UFW
  ufw:
    state: enable
    policy: allow
    logging: 'on'

- name: Allow port through firewall for webserver UFW
  ufw:
    rule:
    port: {{ http_port }}
    proto: tcp

- name: Allow port through firewalld for webserver https
  ufw:
    rule:
      port: {{ https_port}}
      proto: tcp
  notify: reload ufw
