---
- name: Enables UFW
  ufw:
    state: enabled
    policy: allow
    logging: 'on'

- name: Allow port through firewall for webserver UFW
  ufw:
    rule: allow
    port: '{{ http_port }}'
    proto: tcp

- name: Allow port through firewalld for webserver https
  ufw:
    rule: allow
    port: '{{ https_port}}'
    proto: tcp
  notify: reloaded ufw
