---
- name: "Install ansible python3 mysql dependency"
  apt:
    name: python3-mysqldb
    state: latest

- name: Install Mysql
  apt:
    name: ['mysql-server', 'mysql-client']
    state: latest
  notify: restart mysql

- name: Create database
  mysql_db:
    name: '{{ mysql_db_name }}'
    state: present


#- name: Add root user to mysql
#  mysql_user:
#    config_file: /etc/mysql/my.cnf
#    login_host: localhost
#    login_user: root    
#    login_password: ""
#    login_port: 3306
#    name: '{{ mysql_user }}'
#    password: '{{ mysql_root_password }}'
#    encrypted: yes
#    priv: '{{ mysql_db_name }}.*ALL'
#    state: present
#    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create user for the database
  mysql_user:
    config_file: /etc/mysql/my.cnf
    login_host: localhost
    login_user: root
    login_password: ""
    login_port: 3306
    name: '{{ mysql_user }}'
    password: '{{ mysql_password }}'
    priv: '{{ mysql_db_name  }}.*:ALL'
    state: present

- name: Remove all anonymous user from mysql
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: ""

- name: Removes mysql test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: ""
  notify: restart mysql
