---
- name: apt-get update
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Update cache if needed
  apt: 
    name: '*'
    state: latest

- name: Setup timezone to Asia/Tashkent
  timezone:
    name: Asia/Tashkent

- name: add repo
  apt_repository:
    repo: 'ppa:ondrej/php'

- name: install php
  apt: name={{ php_version }}-fpm  state=latest

- name: install php depencies
  apt:
    name: '{{ php_depencies }}'
    state: present

- name: configure php.ini
  blockinfile:
    dest: /etc/php/8.0/fpm/php.ini
    block: |
      date.time = Asia/Tashkent
      cgi-fix_pathinfo = 0
    backup: yes
  notify: restart php-fpm
